apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
    - port: 80          # Port exposed by the service
      targetPort: 3000  # Port your app container listens on
      protocol: TCP
      name: http

