apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
    - port: 80         
      targetPort: 3000 
      protocol: TCP
      name: http

